export const types = {
	CREATE_NEWS: 'NEWS/CREATE_NEWS',
	FETCH_NEWS: 'NEWS/FETCH_NEWS',
	NEWS_RESULT: 'NEWS/NEWS_RESULT',
	FETCH_ALL_NEWS: 'NEWS/FETCH_ALL_NEWS',
	ALL_NEWS_RESULT: 'NEWS/ALL_NEWS_RESULT',
	DELETE_NEWS: 'NEWS/DELETE_NEWS',
	UPDATE_NEWS: 'NEWS/UPDATE_NEWS',
};
