export const endPoints = {
    login: "user/login",
    register: "user",
    usersLoad: "users_load",
    forgotPassword: "user_forgot_password",
    userLoad: "user",
    userUpdate: "user",
    createCompany: "company",
    updateCompany: "company/update/",
    updateEmployee: "company/employee",
    deleteEmployee: "company/employee",
    companyLoad: "company/",
    uploadImage: "file-upload/image",
    uploadFile: "file-upload/etc",
    createJob: "job",
    fetchAllJobs: "job",
    fetchJob: "job/detail",
    fetchEmployeeJobs: "job/employee",
    updateJobSettings: "job/update-settings",
};
