export const CREATE_COMPANY = "COMPANY/CREATE_COMPANY";
export const FETCH_COMPANY = "COMPANY/FETCH_COMPANY";
export const COMPANY_RESULT = "COMPANY/COMPANY_RESULT";
export const UPDATE_COMPANY = "COMPANY/UPDATE_COMPANY";
export const SUBMIT_END = "COMPANY/SUBMIT_END";
export const IMAGE_UPLOAD = 'COMPANY/IMAGE_UPLOAD';
