export const FETCH_COMPANY = "USER/FETCH_COMPANY";
export const COMPANY_RESULT = "USER/COMPANY_RESULT";
export const UPDATE_COMPANY = "USER/UPDATE_COMPANY";
export const UPDATE_COMPANY_END = "USER/UPDATE_COMPANY_END";
export const UPDATE_COMPANY_SUCCESS = "USER/UPDATE_COMPANY_SUCCESS";
