export const FETCH_USER = "USER/FETCH_USER";
export const USER_RESULT = "USER/USER_RESULT";
export const UPDATE_USER = "USER/UPDATE_USER";
export const UPDATE_USER_END = "USER/UPDATE_USER_END";
export const UPDATE_USER_SUCCESS = "USER/UPDATE_USER_SUCCESS";
export const USER_COMPANY = "USER/USER_COMPANY";
